name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm install --save-dev @types/node @types/jest @types/mocha
    - run: npm install --save-dev @types/assert @types/net @types/path @types/fs @types/worker_threads @types/ps-list
    - run: npm run build
    - run: npm test